f = open('../data/example.in')
data = f.readlines()
print(data)
numbers = data[0].split(' ')
print(numbers)
R = int(numbers[0])
C = int(numbers[1])
L = int(numbers[2])
H = int(numbers[3])
print(R, C, L, H)
